### PR TITLE
[WIP] migrate connector v10

### PR DESCRIPTION
**Pull request by bguillot**
Hello, 

Here is the following of my devs to port the connector to v10.
More to come in the next days.

The buttons to synchronize metadata and base data are now working. 
I will continue to migrate components and fix the import of the sale orders and dependecies.

(I reopen a PR because the previous one has been merged)

Thanks !

### CODE REVIEW

**Comment by sergio-teruel** [comment]
@bguillot Thanks for your help... :smiley: 
When you tell me, I merge it.

**Comment by xavierjimenez** [comment]
Hello,

Recently I've been working on the connector_prestashop because we also want to have it for 10.0. Unfortunately, I've done more or less the same work as you guys (my bad, I last checked it out a few days ago) so I would like to know on what you are going to focus next to not repeat the same again, I was thinking on starting the customer importation but I don't know if you already started that. Please let me know!

Good work and thanks! @bguillot

**Comment by pedrobaeza** [comment]
@bguillot maybe it's better to propose directly your changes to OCA for having better visibility, and close our PR.

**Comment by flotho** [comment]
Hi @xavierjimenez ,

We saw your post a little late with @bguillot .
From now what it will be done :
* This PR will be closed by @bguillot 
* @bguillot will propose a PR to OCA from it's repo https://github.com/akretion/connector-prestashop (recommended by @pedrobaeza )
* @bguillot will review all the PR I'll propose in his repo. You can do the same if you want.

What has be done for the moment https://github.com/akretion/connector-prestashop/pull/2
* All the importation process works :
  - Products / variants attributes etc...
  - partners importation works etc...
  - Sale order importation works

Next steps for us :
* I personnaly will make more tests and debugs on this importation process
* @bguillot is starting to migrate the exportation process with listener parts etc...

maybe you could propose something on this exportation part, there are so much to do :
* Stocks
* Order states
* catalog Manager, etc... (this one could be proposed as an autonomous PR)

Hope we answer to your questions,

regards

**Comment by pedrobaeza** [comment]
catalog_manager is already proposed as PR in https://github.com/OCA/connector-prestashop/pull/91

**Comment by xavierjimenez** [comment]
Great, good work and thanks for answering @flotho.

For now I will also test everything done so far, if I find something I will report it and then I can focus on new things.

I'll keep checking your PR.

Regards,

**Review by rafaelbn — APPROVED** [review]
@sergio-teruel @pedrobaeza  please take a look thanks!

**Comment by FFernandez-PlanetaTIC** [comment]
Hello,

PR OCA/product-attribute#359 migrates module product_multi_image to version 10.0 but it's pending review.

Once merged module connector_prestashop could depend on product_multi_image instead of base_multi_image to view imported images in products.

Thanks for this great work!

**Comment by FFernandez-PlanetaTIC** [comment]
Hi,

I've been doing some testing:

### From Backend
- [x] Synchronize metadata
- [x] Synchronize base data
- [x] Import customer groups and customers
- [x] Import product categories and products
  - [ ] View imported images in products - OCA/product-attribute#359
  - [ ] ~~[9.0] Import images in the correct order - I think that Prestashop API doesn't allow to get position or "cover" from images~~
  - [ ] [9.0] Associate images to the correct variants - OCA/product-attribute#359 and akretion/connector-prestashop#4
- [x] Import payment modes
  - [x] [9.0] Do not duplicate payment modes for each language - akretion/connector-prestashop#4 Payment modes are binded by name therefore must be translated
- [x] Import sale orders
  - [x] [9.0] Do not set default product taxes if they are unset in Prestashop - akretion/connector-prestashop#4
- [ ] Import refunds
- [x] Import suppliers
  - [x] [9.0] Import supplier prices - akretion/connector-prestashop#4
- [x] Import carriers
- [x] Export stock quantities
  - [x] Fails for variants with "PrestaShopWebServiceError: 'This filter does not exist. Did you mean: "id_shop"? ...'" - 466db48
- [x] Import stock quantities
  - [x] [9.0] Stock quantities imported are incorrect if product has variants - akretion/connector-prestashop#4

### On sale order change
- [x] Order state is exported

### On stock quantity change
- [x] Product quantity is exported when template stock changes
- [x] Combination quantity is not exported when variant stock changes -  akretion/connector-prestashop#4

~~I've been marked some features as done even if they have issues. I think that these issues could be fixed later since they also apply for version 9.0.~~

Regards!

**Comment by FFernandez-PlanetaTIC** [comment]
Hello,

I've fixed the issues of the previous comment in PR akretion/connector-prestashop#4.

I remain at your disposal for any action needed.

Thanks.

**Comment by bguillot** [comment]
Thanks @FFernandez-PlanetaTIC for the fixes.

@pedrobaeza @sergio-teruel I think the PR is ready to be merged (it is in production for one month at my customer it works well)

**Comment by pedrobaeza** [comment]
Perfect. I'm on holidays this week. Next week I'll improve the commit history and merge. Thanks all for the efforts.

**Pull request merged**
